### ISSUE TITLE
http://cdp-liquidator.surge.sh/ Errors

### ISSUE THREAD

**Issue by rmonsurate** [xwvvvvwx/liquidator#3]
Trying to set up a proxy with a metamask wallet shows ALERT: Trying to call a function on a non-contract address.

**Comment by rmonsurate** [comment]
Also there doesn't seem to be a security certificate for the site. Can't make an https connection.

**Comment by d-xo** [comment]
@rmonsurate this was a hackathon project and is not actively maintained (or fully working), I don't think we're gonna put any effort into tidying this up right now.
